#!/bin/sh
set -e

REPLICATION_USER="${REPLICATION_USER:-repuser}"
REPLICATION_PASSWORD="${REPLICATION_PASSWORD:-repuser}"

USER_ESCAPED=$(printf "%s" "$REPLICATION_USER" | sed "s/'/''/g")
PASS_ESCAPED=$(printf "%s" "$REPLICATION_PASSWORD" | sed "s/'/''/g")

DO_BLOCK=$(cat <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${USER_ESCAPED}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN REPLICATION PASSWORD %L', '${USER_ESCAPED}', '${PASS_ESCAPED}');
    ELSE
        EXECUTE format('ALTER ROLE %I WITH REPLICATION PASSWORD %L', '${USER_ESCAPED}', '${PASS_ESCAPED}');
    END IF;

    EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), '${USER_ESCAPED}');
    EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${USER_ESCAPED}');
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA public TO %I', '${USER_ESCAPED}');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO %I', '${USER_ESCAPED}');
END
\$\$;
SQL
)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "$DO_BLOCK"
