#!/bin/sh
set -e

REPLICATION_USER="${REPLICATION_USER:-repuser}"
REPLICATION_PASSWORD="${REPLICATION_PASSWORD:-repuser}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${REPLICATION_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN REPLICATION PASSWORD %L', '${REPLICATION_USER}', '${REPLICATION_PASSWORD}');
    ELSE
        EXECUTE format('ALTER ROLE %I WITH REPLICATION PASSWORD %L', '${REPLICATION_USER}', '${REPLICATION_PASSWORD}');
    END IF;
END
$$;

DO \$\$
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), '${REPLICATION_USER}');
END
$$;

EXECUTE 'GRANT USAGE ON SCHEMA public TO ' || quote_ident('${REPLICATION_USER}');
EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO ' || quote_ident('${REPLICATION_USER}');
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO PUBLIC;
SQL
